"""Briefing orchestrator.

Runs every probe for the active env, optionally launches a Haiku-powered
"likely cause" assessment for each anomaly, assembles a markdown brief, and
persists it. The whole flow is bounded — total cost per run is well under
$0.005 (4 short Haiku calls + 4 kubectl shells).
"""
from __future__ import annotations

import asyncio
import time
from datetime import datetime, timezone
from typing import Iterable

from anthropic import Anthropic

from apps.api import store
from apps.api.env_context import active_env
from apps.api.proactive.probes import ProbeResult, run_all_probes
from apps.api.settings import get_settings


_SEVERITY_RANK = {"green": 0, "yellow": 1, "red": 2}
_EMOJI = {"green": "✅", "yellow": "🟡", "red": "🔴"}


def _aggregate_severity(results: Iterable[ProbeResult]) -> str:
    rank = max((_SEVERITY_RANK.get(r.severity, 0) for r in results), default=0)
    return {0: "green", 1: "yellow", 2: "red"}[rank]


def _likely_cause(probe: ProbeResult, env: str) -> str:
    """Ask Haiku for a 2-3 sentence likely-cause + suggested-next-step.
    Bounded: max_tokens=200, no tool use."""
    s = get_settings()
    if not s.anthropic_api_key:
        return "(Anthropic key not configured — set ANTHROPIC_API_KEY to enable cause analysis.)"
    client = Anthropic(api_key=s.anthropic_api_key)
    user_msg = (
        f"You are Sherlock, an SRE assistant for the Trackonomy IoT platform.\n\n"
        f"A health probe just fired in env={env}:\n"
        f"  Probe: {probe.name}\n"
        f"  Severity: {probe.severity}\n"
        f"  Summary: {probe.summary}\n"
    )
    if probe.evidence:
        user_msg += "  Evidence:\n"
        for e in probe.evidence:
            user_msg += f"    - {e[:240]}\n"
    user_msg += (
        "\nIn 2-3 sentences, give:\n"
        "1. The most likely cause (be specific to Trackonomy services if the evidence allows).\n"
        "2. ONE concrete next step a human could take RIGHT NOW (a kubectl/sql/Sherlock query).\n"
        "Plain text only. No headings."
    )
    try:
        resp = client.messages.create(
            model="claude-haiku-4-5",
            max_tokens=200,
            messages=[{"role": "user", "content": user_msg}],
        )
        return "".join(b.text for b in resp.content if hasattr(b, "text")).strip()
    except Exception as e:
        return f"(cause analysis skipped: {type(e).__name__})"


def _render_markdown(
    *, env: str, system: str, results: list[ProbeResult],
    causes: dict[str, str], generated_at: str, severity: str,
) -> tuple[str, str, str]:
    """Render the final brief. Returns (title, summary, content_md)."""
    anomalies = [r for r in results if r.anomaly]
    clean = [r for r in results if not r.anomaly]
    n_red = sum(1 for r in anomalies if r.severity == "red")
    n_yellow = sum(1 for r in anomalies if r.severity == "yellow")

    if not anomalies:
        title = f"All systems clean ({env})"
        summary = f"{len(results)} probes clean — no action needed."
    else:
        bits = []
        if n_red:
            bits.append(f"{n_red} red")
        if n_yellow:
            bits.append(f"{n_yellow} yellow")
        title = f"{', '.join(bits)} anomalies in {env}"
        summary = (
            f"{len(anomalies)} anomalies surfaced ({', '.join(bits)}). "
            f"{len(clean)} probes clean."
        )

    lines: list[str] = []
    lines.append(f"# Sherlock Brief — {generated_at}")
    lines.append("")
    lines.append(f"**Env:** `{env}` · **DB system:** `{system}` · **Severity:** {_EMOJI[severity]} `{severity}`")
    lines.append("")
    lines.append(f"**Headline:** {summary}")
    lines.append("")

    if anomalies:
        # Sort red first, then yellow
        anomalies.sort(key=lambda r: -_SEVERITY_RANK[r.severity])
        for r in anomalies:
            lines.append(f"## {_EMOJI[r.severity]} `{r.name}` — {r.severity}")
            lines.append("")
            lines.append(r.summary)
            lines.append("")
            if r.evidence:
                lines.append("**Evidence**")
                lines.append("")
                for e in r.evidence:
                    lines.append(f"> {e}")
                    lines.append("")
            cause = causes.get(r.name)
            if cause:
                lines.append("**Likely cause + next step (Haiku assessment):**")
                lines.append("")
                lines.append(cause)
                lines.append("")
            lines.append("---")
            lines.append("")

    if clean:
        lines.append("## ✅ Clean probes")
        lines.append("")
        for r in clean:
            lines.append(f"- `{r.name}` — {r.summary}")
        lines.append("")

    lines.append("---")
    lines.append(
        f"_Generated by Sherlock proactive mode at {generated_at}. Re-run any time via "
        f"`POST /api/briefings/run` or wait for the next scheduled tick._"
    )
    return title, summary, "\n".join(lines)


async def run_briefing(*, triggered_by: str = "manual") -> dict:
    """Execute one full briefing cycle. Returns the persisted briefing record."""
    s = get_settings()
    env = (active_env.get() or s.sherlock_default_env).lower()
    system = "postgres"
    cfg = s.env_config(env)

    t0 = time.monotonic()
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # Run probes in parallel
    results = await run_all_probes(cfg)

    # For each anomaly, ask Haiku for a likely-cause assessment in parallel.
    anomalies = [r for r in results if r.anomaly]
    if anomalies:
        cause_tasks = [asyncio.to_thread(_likely_cause, r, env) for r in anomalies]
        cause_strs = await asyncio.gather(*cause_tasks)
        causes = {r.name: c for r, c in zip(anomalies, cause_strs)}
    else:
        causes = {}

    severity = _aggregate_severity(results)
    title, summary, content_md = _render_markdown(
        env=env, system=system, results=results, causes=causes,
        generated_at=generated_at, severity=severity,
    )
    duration_ms = int((time.monotonic() - t0) * 1000)

    bid = store.insert_briefing(
        env=env, system=system, severity=severity,
        title=title, summary=summary, content_md=content_md,
        probes=[r.to_dict() for r in results],
        triggered_by=triggered_by, duration_ms=duration_ms,
    )

    return {
        "id": bid,
        "env": env,
        "system": system,
        "severity": severity,
        "title": title,
        "summary": summary,
        "anomalies": len(anomalies),
        "duration_ms": duration_ms,
        "triggered_by": triggered_by,
    }
